### ISSUE TITLE
Peak Definition Doesn't Load

### ISSUE THREAD

**Issue by davidCburke** [ChuckJonas/vscode-apex-autocomplete#22]
Hi,

When peaking definition the window appears with the word loading but that's as far as it gets. 

I'm running Windows 10, Thanks

Output below:

`Sending CMD: --action=findSymbol  --projectPath='c:\Mavensmate\Emerald_Dev_Grain_Mate' --responseFilePath='C:\Users\david\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.10\bin\findSymbolResult.json' --pollWaitMillis=1000 --maxPollRequests=1000 --currentFilePath='c:\Mavensmate\Emerald_Dev_Grain_Mate\src\classes\GrowerPortalController.cls' --currentFileContentPath='C:\Users\david\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.10\bin\findSymbolTmp.cls' --line='4100' --column='31' 

Awaiting connection...

[INFO] SourceScanner - scanning file: findSymbolTmp.cls

[INFO] Executor - # Time taken: 27.879s`

**Comment by ChuckJonas** [comment]
for some reason, peak definition only seems to work if you have the app authenticated with your org.  Have you tried that?

**Comment by jerhewet** [comment]
In my case the request to get definitions seems to be crashing.

Awaiting connection...

Client connected from /127.0.0.1:51120

received command: --action=listCompletions  --projectPath='[path removed]' --responseFilePath='[%USER%]\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\listCompletionsResult.json' --pollWaitMillis=1000 --maxPollRequests=1000 --currentFilePath='[path removed]\force-app\main\default\classes\[my class].cls' --currentFileContentPath='[%USER%]\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\listCompletionsTmp.cls' --line='12' --column='18'  --sf.username='[my SF username]' --sf.password='[my SF password]' --sf.serverurl='[my SF sandbox URL]'

[ERROR] [05/19/2020 09:42:34.436] [TcpServerSystem-akka.actor.default-dispatcher-9] [akka://TcpServerSystem/user/$B] 1
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.neowit.CommandProcessor$$anonfun$5.apply(TcpServer.scala:210)
	at com.neowit.CommandProcessor$$anonfun$5.apply(TcpServer.scala:208)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at com.neowit.CommandProcessor.processCommand(TcpServer.scala:208)
	at com.neowit.CommandProcessor$$anonfun$receive$2.applyOrElse(TcpServer.scala:163)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at com.neowit.CommandProcessor.aroundReceive(TcpServer.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
