### ISSUE TITLE
Autocomplete is not working 

### ISSUE THREAD

**Issue by khmerforce** [ChuckJonas/vscode-apex-autocomplete#34]
This is what I get from the Apex Autocomplete Output. Do you have any idea why?

Starting Language Server. CMD: java -Dfile.encoding=UTF-8  -jar "c:\Users\khmerforce\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\tooling-force.jar" --action=serverStart --port=65000 --timeoutSec=1800
[ERROR] Executor - java.net.BindException: Address already in use: JVM_Bind

[ERROR] Executor - 	at java.net.DualStackPlainSocketImpl.bind0(Native Method)

[ERROR] Executor - 	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)

[ERROR] Executor - 	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)

[ERROR] Executor - 	at java.net.PlainSocketImpl.bind(Unknown Source)

[ERROR] Executor - 	at java.net.ServerSocket.bind(Unknown Source)

[ERROR] Executor - 	at java.net.ServerSocket.<init>(Unknown Source)

[ERROR] Executor - 	at java.net.ServerSocket.<init>(Unknown Source)

[ERROR] Executor - 	at com.neowit.TcpServer.<init>(TcpServer.scala:88)

[ERROR] Executor - 	at com.neowit.ServerStart.act(TcpServer.scala:49)

[ERROR] Executor - 	at com.neowit.apex.actions.Action$class.execute(Action.scala:93)

[ERROR] Executor - 	at com.neowit.apex.actions.AsyncAction.execute(Action.scala:115)

[ERROR] Executor - 	at com.neowit.apex.Executor.run(Runner.scala:139)

[ERROR] Executor - 	at com.neowit.apex.Executor.execute(Runner.scala:52)

[ERROR] Executor - 	at com.neowit.apex.Runner$.main(Runner.scala:36)

[ERROR] Executor - 	at com.neowit.apex.Runner.main(Runner.scala)

[ERROR] Executor - java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at com.neowit.TcpServer.<init>(TcpServer.scala:88)
	at com.neowit.ServerStart.act(TcpServer.scala:49)
	at com.neowit.apex.actions.Action$class.execute(Action.scala:93)
	at com.neowit.apex.actions.AsyncAction.execute(Action.scala:115)
	at com.neowit.apex.Executor.run(Runner.scala:139)
	at com.neowit.apex.Executor.execute(Runner.scala:52)
	at com.neowit.apex.Runner$.main(Runner.scala:36)
	at com.neowit.apex.Runner.main(Runner.scala)

java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at com.neowit.TcpServer.<init>(TcpServer.scala:88)
	at com.neowit.ServerStart.act(TcpServer.scala:49)
	at com.neowit.apex.actions.Action$class.execute(Action.scala:93)
	at com.neowit.apex.actions.AsyncAction.execute(Action.scala:115)
	at com.neowit.apex.Executor.run(Runner.scala:139)
	at com.neowit.apex.Executor.execute(Runner.scala:52)
	at com.neowit.apex.Runner$.main(Runner.scala:36)
	at com.neowit.apex.Runner.main(Runner.scala)

RESULT=FAILURE

MESSAGE: {"id":1,"text":"Address already in use: JVM_Bind","type":"ERROR"}

**Comment by khmerforce** [comment]
I try to peek definition and it doesn't work also. Please help.

**Comment by ChuckJonas** [comment]
Looks like something else is already running on the same port that the tooling-force service is attempting to start on.  See this [StackOverflow post](https://stackoverflow.com/questions/2772701/address-already-in-use-jvm-bind-java) on how to debug

**Comment by khmerforce** [comment]
@ChuckJonas This is what I get from the output. Not sure why...

Sending CMD: --action=findSymbol  --projectPath='c:\Users\testing\salesforce-code' --responseFilePath='c:\Users\testing\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\findSymbolResult.json' --pollWaitMillis=1000 --maxPollRequests=1000 --currentFilePath='c:\Users\testing\salesforce-code\Apptest\force-app\main\default\classes\CrudImanageOpp.cls' --currentFileContentPath='c:\Users\testing\.vscode\extensions\chuckjonas.apex-autocomplete-0.2.13\bin\findSymbolTmp.cls' --line='24' --column='52'  --sf.username='johnexample@example.apptest' --sf.password='wording' --sf.serverurl='https://test.salesforce.com'

Awaiting connection...

[ERROR] Executor - com.neowit.utils.ConfigValueException: failed to detect 'src' folder in path:c:\Users\testing\salesforce-code

[ERROR] Executor - 	at com.neowit.utils.ConfigWithSfdcProject.srcDirOpt$lzycompute(Config.scala:270)

[ERROR] Executor - 	at com.neowit.utils.ConfigWithSfdcProject.srcDirOpt(Config.scala:265)

[ERROR] Executor - 	at com.neowit.apex.actions.ScanSource.getRecognisedApexFiles(ScanSource.scala:106)

[ERROR] Executor - 	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FindSymbol.scala:79)


[ERROR] Executor - 	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FindSymbol.scala:68)

[ERROR] Executor - 	at scala.Option.map(Option.scala:146)


[ERROR] Executor - 	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1.apply(FindSymbol.scala:68)

[ERROR] Executor - 	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1.apply(FindSymbol.scala:67)

[ERROR] Executor - 	at scala.Option.flatMap(Option.scala:171)

[ERROR] Executor - 	at com.neowit.apex.actions.FindSymbol$$anonfun$1.apply(FindSymbol.scala:67)

[ERROR] Executor - 	at com.neowit.apex.actions.FindSymbol$$anonfun$1.apply(FindSymbol.scala:66)

[ERROR] Executor - 	at scala.Option.flatMap(Option.scala:171)


[ERROR] Executor - 	at com.neowit.apex.actions.FindSymbol.act(FindSymbol.scala:66)

[ERROR] Executor - 	at com.neowit.apex.actions.Action$class.execute(Action.scala:93)

[ERROR] Executor - 	at com.neowit.apex.actions.AsyncAction.execute(Action.scala:115)

[ERROR] Executor - 	at com.neowit.apex.Executor.run(Runner.scala:139)

[ERROR] Executor - 	at com.neowit.apex.Executor.execute(Runner.scala:52)

[ERROR] Executor - 	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(TcpServer.scala:220)

[ERROR] Executor - 	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply(TcpServer.scala:218)

[ERROR] Executor - 	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply(TcpServer.scala:218)

[ERROR] Executor - 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)

[ERROR] Executor - 	at scala.Console$.withOut(Console.scala:53)

[ERROR] Executor - 	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply$mcI$sp(TcpServer.scala:218)

[ERROR] Executor - 	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply(TcpServer.scala:218)

[ERROR] Executor - 	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply(TcpServer.scala:218)

[ERROR] Executor - 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)

[ERROR] Executor - 	at scala.Console$.withErr(Console.scala:80)

[ERROR] Executor - 	at com.neowit.CommandProcessor.processCommand(TcpServer.scala:217)

[ERROR] Executor - 	at com.neowit.CommandProcessor$$anonfun$receive$2.applyOrElse(TcpServer.scala:163)

[ERROR] Executor - 	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)

[ERROR] Executor - 	at com.neowit.CommandProcessor.aroundReceive(TcpServer.scala:159)

[ERROR] Executor - 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)

[ERROR] Executor - 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)

[ERROR] Executor - 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)


[ERROR] Executor - 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)

[ERROR] Executor - 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

[ERROR] Executor - 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

[ERROR] Executor - 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

[ERROR] Executor - 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

[ERROR] Executor - 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


[ERROR] Executor - com.neowit.utils.ConfigValueException: failed to detect 'src' folder in path:c:\Users\testing\salesforce-code
	at com.neowit.utils.ConfigWithSfdcProject.srcDirOpt$lzycompute(Config.scala:270)
	at com.neowit.utils.ConfigWithSfdcProject.srcDirOpt(Config.scala:265)
	at com.neowit.apex.actions.ScanSource.getRecognisedApexFiles(ScanSource.scala:106)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FindSymbol.scala:79)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FindSymbol.scala:68)
	at scala.Option.map(Option.scala:146)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1.apply(FindSymbol.scala:68)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1.apply(FindSymbol.scala:67)
	at scala.Option.flatMap(Option.scala:171)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1.apply(FindSymbol.scala:67)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1.apply(FindSymbol.scala:66)
	at scala.Option.flatMap(Option.scala:171)
	at com.neowit.apex.actions.FindSymbol.act(FindSymbol.scala:66)
	at com.neowit.apex.actions.Action$class.execute(Action.scala:93)
	at com.neowit.apex.actions.AsyncAction.execute(Action.scala:115)
	at com.neowit.apex.Executor.run(Runner.scala:139)
	at com.neowit.apex.Executor.execute(Runner.scala:52)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(TcpServer.scala:220)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply(TcpServer.scala:218)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply(TcpServer.scala:218)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:53)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply$mcI$sp(TcpServer.scala:218)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply(TcpServer.scala:218)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply(TcpServer.scala:218)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:80)
	at com.neowit.CommandProcessor.processCommand(TcpServer.scala:217)
	at com.neowit.CommandProcessor$$anonfun$receive$2.applyOrElse(TcpServer.scala:163)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at com.neowit.CommandProcessor.aroundReceive(TcpServer.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)



com.neowit.utils.ConfigValueException: failed to detect 'src' folder in path:c:\Users\testing\salesforce-code
	at com.neowit.utils.ConfigWithSfdcProject.srcDirOpt$lzycompute(Config.scala:270)
	at com.neowit.utils.ConfigWithSfdcProject.srcDirOpt(Config.scala:265)
	at com.neowit.apex.actions.ScanSource.getRecognisedApexFiles(ScanSource.scala:106)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FindSymbol.scala:79)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2.apply(FindSymbol.scala:68)
	at scala.Option.map(Option.scala:146)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1.apply(FindSymbol.scala:68)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1$$anonfun$apply$1.apply(FindSymbol.scala:67)
	at scala.Option.flatMap(Option.scala:171)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1.apply(FindSymbol.scala:67)
	at com.neowit.apex.actions.FindSymbol$$anonfun$1.apply(FindSymbol.scala:66)
	at scala.Option.flatMap(Option.scala:171)
	at com.neowit.apex.actions.FindSymbol.act(FindSymbol.scala:66)
	at com.neowit.apex.actions.Action$class.execute(Action.scala:93)
	at com.neowit.apex.actions.AsyncAction.execute(Action.scala:115)
	at com.neowit.apex.Executor.run(Runner.scala:139)
	at com.neowit.apex.Executor.execute(Runner.scala:52)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(TcpServer.scala:220)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply(TcpServer.scala:218)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1$$anonfun$apply$mcI$sp$1.apply(TcpServer.scala:218)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:53)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply$mcI$sp(TcpServer.scala:218)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply(TcpServer.scala:218)
	at com.neowit.CommandProcessor$$anonfun$processCommand$1.apply(TcpServer.scala:218)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:80)
	at com.neowit.CommandProcessor.processCommand(TcpServer.scala:217)
	at com.neowit.CommandProcessor$$anonfun$receive$2.applyOrElse(TcpServer.scala:163)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
	at com.neowit.CommandProcessor.aroundReceive(TcpServer.scala:159)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
